@isTest
public class DemoTest {

	@isTest		//Annotation for Test Method
    static void testDisplay() {
        /*
        //Since we do not need input to test this method, no Setup Data created
        
        //Starting to Test the method
        Test.startTest();

        // Call the method to test
        apexPractise.display();

        //Ending the Test for the method
        Test.stopTest();

        // Since we can't assert debug log output directly, consider testing outcomes
        // For example, if the displayValues method had a return value, you could assert that value
        */ 
    }
}